### ISSUE TITLE
IAM ARN as master user

### ISSUE THREAD

**Issue by nkhine** [aws-samples/amazon-elasticsearch-service-with-cognito#1]
Hello,
Thank you for the template, how do you enable the master user, as per https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/fgac.html#fgac-walkthrough-iam ?

i see we have https://github.com/aws-samples/amazon-elasticsearch-service-with-cognito/blob/master/lib/search-stack.ts#L51-L56 but we are missing the Group to attach this user to

**Comment by steffeng** [comment]
Hi Norman, yes, this template has been created prior to the release of Fine Grained Access Control for Amazon Elasticsearch Service. I'm sorry but currently, the Amazon Elasticsearch Service domain is launched without the prereqs from [the docs](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/fgac.html#fgac-walkthrough-iam). You need to adapt the template yourself. I filed a feature request in #2.

**Comment by steffeng** [comment]
Fine-grained access control has been implemented with #2.
