### ISSUE TITLE
Cannot deploy v1.1.0: CustomResource attribute error: Vendor response doesn't contain UserPoolClients.0.ClientId on roleMappingsJson create

### ISSUE THREAD

**Issue by chicken-noodle-chris** [aws-samples/amazon-elasticsearch-service-with-cognito#4]
When deploying through the serverless app repository (the deploy button in the README), CloudFormation fails to create roleMappingsJson, with a CustomResource attribute error, which then initiates a rollback: 

`CustomResource attribute error: Vendor response doesn't contain UserPoolClients.0.ClientId key in object arn:aws:cloudformation:us-east-1:[Account ID]:stack/serverlessrepo-amazon-elasticsearch-service-with-cognito/c2fc65f0-330b-11eb-905f-12605691f9eb|clientIdResource4DD3A5C0|e99df157-3d7e-4f4d-9730-1e6b99e870d5 in S3 bucket cloudformation-custom-resource-storage-useast1`

When deploying through the CDK CLI after downloading the repo, I first get an error about needing to bootstrap the account, so I run `cdk bootstrap aws://[Account ID]/us-east-1`, per the error, and then I run the deploy command again. It runs for a bit, but ultimately hits the same error as deploying from the app repository:  

> 17/25 | 9:26:25 AM | CREATE_FAILED        | Custom::AWSCDKCfnJson                    | roleMappingsJson/Resource/Default (roleMappingsJson77641558) **CustomResource attribute error: Vendor response doesn't conta                                                             in UserPoolClients.0.ClientId key in object arn:aws:cloudformation:us-east-1:[Account ID]:stack/searchStack/50f9b440-330f-11eb-8524-0a2cf6192d53|clientIdResource4DD3A5C0|6959591b-c407-449a-a94d-593625206197 in                                                              S3 bucket cloudformation-custom-resource-storage-useast1**
>         new CustomResource (C:\Users\cpickard\DevOps\amazon-elasticsearch-service-with-cognito-1.1.0\node_modules\@aws-cdk\core\lib\custom-resource.ts:115:21)
>         \_ new CfnJson (C:\Users\cpickard\DevOps\amazon-elasticsearch-service-with-cognito-1.1.0\node_modules\@aws-cdk\core\lib\cfn-json.ts:58:22)
>         \_ new SearchStack (C:\Users\cpickard\DevOps\amazon-elasticsearch-service-with-cognito-1.1.0\lib\search-stack.ts:158:21)
>         \_ Object.<anonymous> (C:\Users\cpickard\DevOps\amazon-elasticsearch-service-with-cognito-1.1.0\bin\search.ts:7:1)
>         \_ Module._compile (internal/modules/cjs/loader.js:1015:30)
>         \_ Module.m._compile (C:\Users\cpickard\DevOps\amazon-elasticsearch-service-with-cognito-1.1.0\node_modules\ts-node\src\index.ts:858:23)
>         \_ Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
>         \_ Object.require.extensions.<computed> [as .ts] (C:\Users\cpickard\DevOps\amazon-elasticsearch-service-with-cognito-1.1.0\node_modules\ts-node\src\index.ts:861:12)
>         \_ Module.load (internal/modules/cjs/loader.js:879:32)
>         \_ Function.Module._load (internal/modules/cjs/loader.js:724:14)
>         \_ Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
>         \_ main (C:\Users\cpickard\DevOps\amazon-elasticsearch-service-with-cognito-1.1.0\node_modules\ts-node\src\bin.ts:227:14)
>         \_ Object.<anonymous> (C:\Users\cpickard\DevOps\amazon-elasticsearch-service-with-cognito-1.1.0\node_modules\ts-node\src\bin.ts:513:3)
>         \_ Module._compile (internal/modules/cjs/loader.js:1015:30)
>         \_ Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
>         \_ Module.load (internal/modules/cjs/loader.js:879:32)
>         \_ Function.Module._load (internal/modules/cjs/loader.js:724:14)
>         \_ Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
>         \_ internal/main/run_main_module.js:17:47
>  17/25 | 9:26:25 AM | CREATE_FAILED        | AWS::Elasticsearch::Domain               | searchDomain Resource creation cancelled
>         new SearchStack (C:\Users\cpickard\DevOps\amazon-elasticsearch-service-with-cognito-1.1.0\lib\search-stack.ts:98:22)
>         \_ Object.<anonymous> (C:\Users\cpickard\DevOps\amazon-elasticsearch-service-with-cognito-1.1.0\bin\search.ts:7:1)
>         \_ Module._compile (internal/modules/cjs/loader.js:1015:30)
>         \_ Module.m._compile (C:\Users\cpickard\DevOps\amazon-elasticsearch-service-with-cognito-1.1.0\node_modules\ts-node\src\index.ts:858:23)
>         \_ Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
>         \_ Object.require.extensions.<computed> [as .ts] (C:\Users\cpickard\DevOps\amazon-elasticsearch-service-with-cognito-1.1.0\node_modules\ts-node\src\index.ts:861:12)
>         \_ Module.load (internal/modules/cjs/loader.js:879:32)
>         \_ Function.Module._load (internal/modules/cjs/loader.js:724:14)
>         \_ Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
>         \_ main (C:\Users\cpickard\DevOps\amazon-elasticsearch-service-with-cognito-1.1.0\node_modules\ts-node\src\bin.ts:227:14)
>         \_ Object.<anonymous> (C:\Users\cpickard\DevOps\amazon-elasticsearch-service-with-cognito-1.1.0\node_modules\ts-node\src\bin.ts:513:3)
>         \_ Module._compile (internal/modules/cjs/loader.js:1015:30)
>         \_ Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
>         \_ Module.load (internal/modules/cjs/loader.js:879:32)
>         \_ Function.Module._load (internal/modules/cjs/loader.js:724:14)
>         \_ Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
>         \_ internal/main/run_main_module.js:17:47

If I download the 1.0.2 release, I can deploy it without issues.

**Comment by steffeng** [comment]
@krazykhris875, thanks for the report.
Investigating...

**Comment by steffeng** [comment]
Thanks again for reaching out @krazykhris875.
Fixed order of resource creation in the code. Deployed to [AWS Serverless Application Repository page](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:387304072572:applications~amazon-elasticsearch-service-with-cognito).
