### ISSUE TITLE
Adding users to multiple cognito groups

### ISSUE THREAD

**Issue by ColeSiegelTR** [aws-samples/amazon-elasticsearch-service-with-cognito#6]
Hi,

When I attempt to login with a Cognito token containing multiple elements in the `cognito:roles` collection, I receive an error: `OpenDistro ES: Missing Role No roles available for this user, please contact your system administrator`.

Is this expected? The sample only includes users that are part of a single cognito group (admin). I'm able to log in if I'm part of a single cognito group but as soon as I am part of multiple, I receive the error above.

I was planning to organize my users into multiple concurrent cognito groups, which map them to different kibana roles to control their access.

**Comment by steffeng** [comment]
Hi @ColeSiegelTR, if possible, please [create a support ticket](https://console.aws.amazon.com/support/home) to look deeper into your configuration with AWS Support. I can't.

Just my guess what could be wrong in your setup:

1. In Amazon Cognito User Pools you can define a precedence for a group. In your case, precedence must be used to select which group is applied for permissions if a user is in multiple groups. The group with the lowest precedence is applied. [Learn more about precedence](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-user-groups.html).
2. You need to map your backend role associated with the new groups in the FGAC setup [as done here](https://github.com/aws-samples/amazon-elasticsearch-service-with-cognito/blob/master/lib/search-stack.ts#L273-L294).

**Comment by ColeSiegelTR** [comment]
Thanks @steffeng I will raise a ticket.

I do have precedence correctly applied, as I mentioned the cognito token does contain multiple elements in the `cognito:roles `collection, these IAM roles are mapped to FGAC kibana roles and work independently. However having multiple roles in cognito:roles seems to break OpenDistro ES and I cannot login, when I expected to have multiple kibana roles assumed.

**Comment by steffeng** [comment]
Sorry I can't you help more. Please keep me posted about the solution from the ticket.

I'm afraid you need to decide for a single group/ IAM role (but potentially mapped to multiple FGAC roles). What's the `cognito:preferred_role` value in your token? If it's not set, mind the [resolution process here](https://docs.aws.amazon.com/cognito/latest/developerguide/role-based-access-control.html#using-tokens-to-assign-roles-to-users).

**Comment by ColeSiegelTR** [comment]
Hi @steffeng 

Are you saying that the re: page which shows `Backend roles (1) - Backend roles you are currently mapped to by your administrator` it is only possible to assume a total of (1) backend role when using the Cognito integration? I assumed multiple were allowed, but perhaps that is the breakdown in my design if only a single IAM role is supported.

**Comment by sparkcatalyst96** [comment]
@steffeng @ColeSiegelTR did you ever find a solution to this? I have multiple Opensearch domains and have created 2 user groups for each domain in cognito, something like:

Domain1:
    domain1Admins
    domain1ReadOnly
Domain2:
    domain2Admins
    domain2ReadOnly
    
If precedence is equal for both (0 and 0 or 1 and 1, etc) and my user is part of domain1Admins and domain2Admins let's say, I get:

`com.amazonaws.services.cognitoidentity.model.NotAuthorizedException: The ambiguous role mapping rules for: cognito-idp.REGION.amazonaws.com/POOL_ID denied this request. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: NotAuthorizedException;`

If I set domain1Admins precedence to 0 and domain2Admins precedence to 1 and try to access Domain1, that will work, but accessing Domain2 will error with:

`No roles available for this user, please contact your system administrator.`
because domain1Admins will be used as it has the lowest precedence.

This means that I can have only 2 groups:
ElasticsearchAdmins
ElasticsearchReadOnly

and assign my users to only one or the other. How can I allow a user to be readOnly for Domain1 and admin for Domain2, for example?

**Comment by ColeSiegelTR** [comment]
Hi @GeorgeCimpoies 

Unfortunately, as far as I learned, the ES/Cognito integration only supports mapping roles based on a single Cognito group/AWS role per Cognito user. Frankly, this makes it not all that useful at all in my opinion.

I ended up creating an AWS role per user as part of a Cognito post confirmation trigger (e.g. User1, User2, User3), and a FGAC ES role for each type of user (LogGroup1/LogGroup2/Admin/Basic) as suggested above. The ES role mapping includes the full list of ARNs for the users who should have that permission. When users login to ES via Cognito they only assume a single AWS role which is the one customized for their own identity. In other words, the Cognito group serves no purpose.

I had to do some work arounds to make this work, overall I wouldn't say I am that happy with the solution because there are some limitations (e.g. number of roles can get unmanageable if there are a lot of users). Probably not even worth using Cognito with ES given this large issue.

**Comment by ColeSiegelTR** [comment]
This is what I got in my support ticket after several follow ups with AWS. Of course grouping the backend roles into one as suggested would not solve my solution as that would mean I cannot separate the access into discrete groups.

```
Thanks for the  details ,I understood the issue .
 
The ES Fine Grained Access Control is designed to map only one backend role with an IAM role  for Cognito token . Will you be able to merge multiple backend roles into one role? ,is this an option?  .This will has the benefit of grouping users with the similar needs ,you’ve less number of Cognito groups and IAM roles to manage.
Srini,
[steffeng 04-02-2022, redacted personal data]
```

**Comment by sparkcatalyst96** [comment]
Thank you for the swift response!

My usecase is pretty straightforwart, I want a developer to have admin access over a staging ES cluster and readonly access over a production ES cluster.

As far as I understand [from the documentation](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-user-groups.html), when you have groups with different precedences, the lowest one is taken so the cognito:prefferedRole is set to the role ARN of the group with the lowest precedence, while cognito:roles is a collection containing the roles of all groups the user is part of.

Architecturally speaking, I would expect Cognito to check for success among all roles in cognito:roles and not stop at cognito:prefferedRole, if that one doesn't offer the necessary permissions.

I understand that you have an IAM role for each user and a Kibana internal role for each user type (admin/readonly/etc) and in Kibana FGAC you map :
 - admin to backend role IAM user 1, 2, 3
 - readonly to backend role IAM user 4,5
 
 However, your implementatios is programmatic I assume ("as part of a Cognito post confirmation trigger"). Is the same result achievable via console? How are your users able to authenticate to multiple ES clusters with Cognito?
 
 Thanks again for your response!

**Comment by sparkcatalyst96** [comment]
https://stackoverflow.com/questions/55180987/aws-cognito-user-pool-group-precedence-working-as-expected-and-useless-or-brok

**Comment by ColeSiegelTR** [comment]
@GeorgeCimpoies 

> Architecturally speaking, I would expect Cognito to check for success among all roles in cognito:roles and not stop at cognito:prefferedRole, if that one doesn't offer the necessary permissions.
>
> I understand that you have an IAM role for each user and a Kibana internal role for each user type (admin/readonly/etc) and in Kibana FGAC you map :
> 
> * admin to backend role IAM user 1, 2, 3
> * readonly to backend role IAM user 4,5


Yeah that's right, because of the limitations of how ES only uses the preferred Cognito token this was the only way I could possibly allow one user to be part of multiple ES permission groups in the same cluster simultaneously. It feels like a bug with the ES/Cognito integration to me, but my support ticket/issues didn't go anywhere.

>
> However, your implementatios is programmatic I assume ("as part of a Cognito post confirmation trigger"). Is the same result achievable via console? How are your users able to authenticate to multiple ES clusters with Cognito?

My use case is a bit different, I don't have the same Cognito user logging in to multiple ES clusters. I have a corresponding Cognito pool for each ES environment. However I understand you are hitting the same limitation as me because you want a single cognito user to assume a collection of different roles when logging in to ES.

The idea behind the Cognito triggers is that you can set up a piece of code (e.g. to create a role/assign a role to a group/manipulate role mappings in ES) that will execute automatically after certain Cognito events, like login or registration. I used these triggers to ensure that my Cognito users had a relevant AWS role to assume, which had corresponding back-end role mappings in ES.

Your use case is a bit more simple than mine since you don't have dynamic permission groups (they are fixed like [admin, readonly]), you might be able to use identity pool rules to map a role to your users based on claims instead of directly via Cognito groups/precedence. https://docs.aws.amazon.com/cognito/latest/developerguide/role-based-access-control.html#using-rules-to-assign-roles-to-users. It didn't work for me since the creation of new permission/ES groups is dynamic in my use case but may be worth a look.

**Comment by sparkcatalyst96** [comment]
Thank you!

**Comment by steffeng** [comment]
Hi @GeorgeCimpoies, I'm afraid I can't help you here with a different implementation in this stack/ code sample. Please also double check with [AWS support](https://console.aws.amazon.com/support/home) for other solutions for your requirement in Amazon Cognito or Amazon OpenSearch Service.
