### ISSUE TITLE
Domain already associated with another user pool

### ISSUE THREAD

**Issue by dejanmarich** [aws-samples/amazon-elasticsearch-service-with-cognito#7]
When i run cdk deploy I constantly get this error. 

`   3/28 |15:35:50 | CREATE_FAILED        | AWS::Cognito::UserPoolDomain             | testUserPool/cognitoDomain (testUserPoolcognitoDomain7717C192) Domain already associated with another user pool. (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: InvalidParameterException; Request ID: 5a259fd0-2a0e-4415-b9cc-e75531176866; Proxy: null)`

Tried on 2 accounts, I can even see some user policies (TestUser) on Cognito service. Is there any version missmatch maybe?

**Comment by steffeng** [comment]
Hi @dejanmarich, sorry to hear that you are having issues to deploy. During the deployment, an Amazon Cognito domain is configured for the hosted UI and your application. The name of the domain is [derived from a few parameters](https://github.com/aws-samples/amazon-elasticsearch-service-with-cognito/blob/master/lib/search-stack.ts#L40) which can collide with an existing domain (by you or another customer). Can you change the `applicationPrefix ` parameter and try again?

**Comment by dejanmarich** [comment]
Hi @steffeng , this actually did the job, i just had to use long and weird domain name :)

**Comment by steffeng** [comment]
Great to hear @dejanmarich. Long and weird domain names are the best. :-)
